version: "3.1"

services:

    db:
        container_name: mvc_db
        image: mysql
        restart: always
        ports:
            
        - 3306:3306
        environment:
          MYSQL_ROOT_PASSWORD: 123456